version: "3.8"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: mlops_backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models:ro   # mount your trained model directory to /app/models
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: mlops_frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped